databaseConfig:
  dbUsername: cs122bg7
  dbPassword: B_EvxR--Y7+0
  dbHostname: localhost
  dbPort: 3308
  dbDriver: com.mysql.cj.jdbc.Driver
  dbName: cs122bg7
  dbSettings: ?autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PST

serviceConfig:
  scheme: http://
  hostName: 0.0.0.0
  port: 5333
  path: /api/idm

loggerConfig:
  outputDir: ./logs/
  outputFile: test.log

sessionConfig:
  timeout: 600000
  expiration: 1800000

